const SearchConstants = {
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
    RESET_SEARCH: 'RESET_SEARCH',
    SET_SEARCH_OVERLAY_DISPLAY: 'SET_SEARCH_OVERLAY_DISPLAY'
}

export default SearchConstants;
