const UserConstants = {
    SET_USER_DATA: 'SET_USER_DATA',
    SET_USER_SAVED_TRACKS: 'SET_USER_SAVED_TRACKS',
    SET_USER_FOLLOWED_ARTISTS: 'SET_USER_FOLLOWED_ARTISTS',
    SET_USER_SAVED_ALBUMS: 'SET_USER_SAVED_ALBUMS'
}

export default UserConstants;
