const CategoriesConstants = {
	'SET_CATEGORIES_DATA': 'SET_CATEGORIES_DATA',
	'SET_SELECTED_CATEGORY': 'SET_SELECTED_CATEGORY',
	'SET_SELECTED_CATEGORY_PLAYLISTS': 'SET_SELECTED_CATEGORY_PLAYLISTS'
}

export default CategoriesConstants;