const PlayerConstants = {
    SET_VOLUME: 'SET_VOLUME',
    SET_AUDIO: 'SET_AUDIO',
    PLAY_AUDIO: 'PLAY_AUDIO',
    PAUSE_AUDIO: 'PAUSE_AUDIO',
    TOGGLE_PLAY_PAUSE: 'TOGGLE_PLAY_PAUSE',
    SET_CURRENT_POSITION: 'SET_CURRENT_POSITION',
    SET_AUDIO_DURATION: 'SET_AUDIO_DURATION',
    SET_PLAYER_QUEUE: 'SET_PLAYER_QUEUE',
    PLAY_PREVIOUS_IN_QUEUE: 'PLAY_PREVIOUS_IN_QUEUE',
    PLAY_NEXT_IN_QUEUE: 'PLAY_NEXT_IN_QUEUE',
    CLEAR_PLAYER_QUEUE: 'CLEAR_PLAYER_QUEUE'
}

export default PlayerConstants;
