const PlayerConstants = {
    SET_VOLUME: 'SET_VOLUME',
    SET_AUDIO: 'SET_AUDIO',
    PLAY_AUDIO: 'PLAY_AUDIO',
    PAUSE_AUDIO: 'PAUSE_AUDIO',
    TOGGLE_PLAY_PAUSE: 'TOGGLE_PLAY_PAUSE',
    SET_CURRENT_POSITION: 'SET_CURRENT_POSITION',
    SET_AUDIO_DURATION: 'SET_AUDIO_DURATION'
}

export default PlayerConstants;
